version: '3'
services:
  web:
    environment:
      SSAPI_SETTINGS: "/app/env/docker.env"
    build: .
    ports:
     - "8083:80"
    restart: always
  worker:
    environment:
      SSAPI_SETTINGS: "/app/env/docker.env"
    build: .
    command: flask rq worker
    restart: always
  redis:
    image: redis:alpine
    restart: always
  db:
    image: mysql:5.7
    restart: always
    env_file:
      - ./env/db.env
      
    
