version: '3'
services:
  web:
    build: .
    ports:
     - "8081:80"
  db:
       image: postgres:alpine
       restart: always
       environment:
         - POSTGRES_USER=test
         - POSTGRES_PASSWORD=test
         - POSTGRES_DB=postgres
       ports:
         - "5433:5432"
       volumes:
         - ./postgres-data:/var/lib/postgresql/data
