version: '3'
services:
  web:
    ports:
      - "5000:80"
    environment:
      SSAPI_SETTINGS: "/app/env/docker.e2e.env"
  worker:
    environment:
      SSAPI_SETTINGS: "/app/env/docker.e2e.env"
  dbe2e:
    image: mysql:5.7
    restart: always
    env_file:
      - ./env/db.e2e.env
    environment:
      E2E_TESTING: "e2e"
    ports:
      - "33060:3306"
    
